# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae8fbbb50a74737359500463f324dbee9b2ea29092cf00a3815208109e11fa9a842d3db3cea1562954240a0cef764b143fc40102a30e7d5a1077b823ebc1ccf

test:
  secret_key_base: 36df239ba76e12001f27378d0b122cb8097e521da3c22551888f00af75ae0ed7712cb9dbcc3fc6e80f8fae435d63111ce9a8f17ab98620a27ba45739e256b13a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
